### ISSUE TITLE
"Incorrect QuickMods Installation" message at game start

### ISSUE THREAD

**Issue by Azzinoth224** [linuxgurugamer/QuickMods#3]
"QuickMods has been installed incorrectly and will not function properly. All files should be located in KSP/GameData/QuickMods. Do not move any files from inside that folder. 

Incorrect path: GameData\QuickMods\QuickStart\Plugins\QuickStart.dll"

I'm getting this message when installing QuickRevert.

**Comment by linuxgurugamer** [comment]
thank you, will fix this evening

**Comment by linuxgurugamer** [comment]
Can you please check to see if this was fixed in the last update?

**Comment by Azzinoth224** [comment]
I can confirm that it is fixed. Thank you.
